+define+COM_MEM_CTRL_W=4
${COM_PATH}/com_define.sv
${COM_PATH}/impl_template/memory/rtl/model/com_tpram_reg.sv
${COM_PATH}/impl_template/memory/rtl/shell/com_spram_shell.sv
${COM_PATH}/common/com_find_lsb_first_one.sv
${COM_PATH}/common/com_arbiter_rr.sv
${COM_PATH}/common/fifo/com_dp_buffer.sv
${COM_PATH}/common/fifo/com_sync_fifo_reg.sv
${COM_PATH}/common/fifo/com_sync_fifo_reg_2w1r.sv
${COM_PATH}/common/fifo/com_sync_fifo_ram_1p2bank.sv
${COM_PATH}/axi/com_axi_extd_wr.sv
${COM_PATH}/axi/com_axi_extd_rd.sv
${COM_PATH}/axi/com_axi_wch_arb.sv
${COM_PATH}/axi/com_axi_wch_regslice.sv
${COM_PATH}/axi/com_axi_wch_clr.sv
${COM_PATH}/axi/com_axi_wch.sv
${COM_PATH}/axi/com_axi_rch_arb.sv
${COM_PATH}/axi/com_axi_rch_regslice.sv
${COM_PATH}/axi/com_axi_rch_clr.sv
${COM_PATH}/axi/com_axi_rch.sv
${COM_PATH}/axi/com_axi_dma.sv
